### ISSUE TITLE
Use zf.namelist() instead of zf.filelist

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/eggshell#40]
https://github.com/bird-house/eggshell/blob/053f164be3202954a38430a800026246a06fd0f1/eggshell/utils.py#L153

I recently placed this function in Raven and realized that `filelist` returns ZipFile objects while `namelist()` returns the strings that `os.path.join()` can use. Feel free to verify that this is indeed the case.

Edit: I'm raising the issue here because I'm fairly certain this usage is erroneous. I've made the modifications in Raven.

**Comment by nilshempelmann** [comment]
Propose to move this to the chat to be discussed there. Its more a question of coding-style. 


Envoyé depuis mon smartphone. 
-------- Message d'origine --------De : Trevor James Smith <notifications@github.com> Date : 12/12/2018  23:41  (GMT+01:00) À : bird-house/eggshell <eggshell@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [bird-house/eggshell] Use zf.namelist() instead of zf.filelist (#40) 
https://github.com/bird-house/eggshell/blob/053f164be3202954a38430a800026246a06fd0f1/eggshell/utils.py#L153
I recently placed this function in Raven and realized that filelist returns ZipFile objects while namelist() returns the strings that os.path.join() can use. Feel free to verify that this is indeed the case.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bird-house/eggshell","title":"bird-house/eggshell","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/bird-house/eggshell"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Use zf.namelist() instead of zf.filelist (#40)"}],"action":{"name":"View Issue","url":"https://github.com/bird-house/eggshell/issues/40"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bird-house/eggshell/issues/40",
"url": "https://github.com/bird-house/eggshell/issues/40",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
